export const minimercado = {
  id: "minimercado",
  slug: "plano-de-negocios-para-minimercado",
    
    // SEO
    metaTitle: "Plano de negócios para minimercado - ECONOMICA UNICAMP",
    metaDescription: "Assegure viabilidade e estratégia com um plano de negócios para minimercado da ECONOMICA. Precificação, receitas, riscos e compliance. Peça sua proposta.",
    metaKeywords: ["plano de negócios para minimercado","plano minimercado","viabilidade minimercado","consultoria minimercado","plano financeiro minimercado","estratégia minimercado"],
    
    // HERO
    heroTitle: "Plano de Negócios para minimercado: Transforme sua Ideia em Sucesso",
    heroSubtitle: "Plano de negócios para minimercado completo pela ECONOMICA: estratégia, viabilidade e gestão para crescer com segurança",
    breadcrumbLabel: "Plano de Negócios para minimercado",
    
    // INTRODUÇÃO
    introducaoH3: "Por que um Plano de Negócios é Essencial para minimercado?",
    introducaoP1: "O setor de minimercado é altamente competitivo: margens apertadas, variação de demanda e concorrência local exigem planejamento estratégico rigoroso. Um plano de negócios para minimercado define modelo de receitas, precificação e captação de clientes, transformando intenção em projeto viável. Com mais de 30 anos de experiência da ECONOMICA, você ganha metodologia comprovada e visão de mercado para reduzir riscos e acelerar resultados.",
    introducaoP2: "Abrir um minimercado sem plano é arriscar a viabilidade financeira e um modelo de negócio incoerente. Sem projeções de receita, estratégia de preço e análise de riscos, empreendimentos sofrem quebras de margem, falta de capital de giro e baixo retorno. Planejamento adequado é a base para decisões financeiras sólidas.",
    
    // BENEFÍCIOS
    beneficiosH3: "O Que Você Ganha com Nosso Plano de Negócios",
    beneficios: [
    { titulo: "Planejamento Estratégico", descricao: "Definimos objetivos claros, metas e rotas estratégicas específicas para seu minimercado com metodologias testadas." },
    { titulo: "Análise Financeira Detalhada", descricao: "Projeções realistas de receitas, custos e rentabilidade que mostram quando e como o minimercado se torna sustentável." },
    { titulo: "Estudo de Mercado", descricao: "Mapeamos concorrência, demanda e perfil do cliente ideal para posicionar seu minimercado de forma competitiva." },
    { titulo: "Projeções de Crescimento", descricao: "Estratégias de expansão e KPIs para crescimento sustentável, com roadmap e metas trimestrais para seu minimercado." }
  ],
    
    // CUSTOS
    custosH3: "O Custo de Não Ter um Plano de Negócios para minimercado",
    custosIntroducao: [
    "Iniciar um minimercado é o sonho de muitos empreendedores, mas paixão e boa vontade não garantem sucesso. Sem planejamento estratégico e gestão profissional, decisões comerciais são tomadas com base em intuição, o que amplifica a exposição a riscos financeiros, falhas no modelo de receitas e perda de competitividade. O setor exige definição clara de precificação, canais de vendas e políticas comerciais que suportem margens e fluxo de caixa; negligenciar esses pontos pode transformar um projeto promissor em uma sequência de prejuízos. Nossa experiência mostra que a diferença entre permanecer no mercado ou fechar as portas passa por análise de viabilidade, mapeamento de clientes e estratégias de captação bem desenhadas.",
    "Muitos enxergam o plano como custo opcional, mas operar sem ele é arriscar capital e tempo. Navegar sem planejamento equivale a investir sem prever retorno: margens corroídas, insucesso na atração de clientes e falta de capital de giro tornam inevitáveis cortes emergenciais que sacrificam diferencial competitivo. Um diagnóstico profissional antecipa pontos de pressão financeira e reduz a probabilidade de decisões reativas que custam caro.",
    "A seguir detalhamos custos invisíveis e concretos que empreendedores de minimercado enfrentam quando não investem em um plano de negócios: impactos estratégicos, financeiros, de mercado, regulatórios e de escalabilidade. Avalie antes de avançar."
  ],
    custos: [
    { titulo: "Precificação Incorreta e Modelo de Receitas Frágil", descricao: "A falta de um modelo de receitas bem definido e de uma estratégia de precificação coerente é uma das falhas mais críticas em minimercados. Sem análise de custo por categoria, margem por produto e elasticidade de preço, proprietários adotarão preços por tentativa e erro, o que resulta em margens insuficientes ou preços acima do mercado que afastam clientes. Você já pensou quantas promoções mal calculadas corroem lucro e fidelidade? Um plano de negócios identifica produtos-chave, define mark-up por categoria, políticas de desconto e ações de cross-selling que mantêm margem e atraem fluxo consistente. Além disso, mapeia fontes de receita complementares relevantes para minimercado, como venda de conveniência, serviços agregados (recarga, bilhetes) e parcerias com delivery, evitando depender exclusivamente do ticket médio. Sem esse roteiro, decisões de preço e oferta ficam desalinhadas com o posicionamento desejado, fragmentando clientes e reduzindo receita por m² comercial.", custoReal: "Erro de precificação pode reduzir margens em 5% a 15%, transformando um faturamento de R$ 50.000 em R$ 2.500 a R$ 7.500 a menos por mês, comprometendo liquidez e reinvestimento." },
    { titulo: "Fluxo de Caixa Desorganizado e Capital de Giro Insuficiente", descricao: "Falhas na gestão financeira são causa frequente de fechamento prematuro de minimercados. Sem projeções de receita realistas e controle rigoroso de custos fixos e variáveis, o caixa entra em desalinho. Muitos empresários subestimam prazos de pagamento a fornecedores, sazonalidade de vendas e necessidade de estoque para atender pico de demanda, gerando falta de capital de giro. A ausência de planejamento do ponto de equilíbrio impede saber quanto vender para cobrir despesas, e decisões como compras por impulso ou renegociação tardia com fornecedores aumentam custos financeiros. Além disso, despesas recorrentes — impostos, taxas estaduais de ICMS, encargos trabalhistas e custos logísticos — tendem a ser negligenciadas na precificação, comprimindo margem operacional. Um plano de negócios detalha projeções mensais, cenários pessimista/realista/otimista, e define estratégias para renegociação de prazos, controle de despesas e necessidade de capital de giro para 6-12 meses, evitando solvência frágil.", custoReal: "Um erro de 10% na projeção de vendas ou na estimativa de capital de giro pode significar um rombo de R$ 10.000 mensais em um minimercado com faturamento projetado de R$ 100.000 por mês." },
    { titulo: "Posicionamento de Mercado Mal Definido", descricao: "Atender o público-alvo errado ou operar sem proposta de valor clara resulta em baixo faturamento e clientes pouco fiéis. Minimercados competem por conveniência, preço e mix de produtos; escolher mal entre competir por preço ou por serviço altera toda a estrutura do negócio. Sem segmentação precisa — definir ICP, entender hábito de compra e basket médio — as ações de marketing e canais de venda são genéricas e ineficazes. Canais inapropriados, como investir pesado em entregas sem avaliar custo por pedido, ou abandonar ofertas de conveniência que atraem fluxo, levam a custos de aquisição elevados e retorno baixo. Além disso, sem um mapa competitivo é difícil identificar oportunidades de diferenciação local, promoções inteligentes e parcerias com fornecedores para private label ou exclusividades. O plano de negócios estabelece posicionamento, mix de canais (balcão, delivery, WhatsApp, app próprio) e táticas de aquisição que maximizam ROI.", custoReal: "Atender o público errado pode reduzir faturamento em 20% a 40%, convertendo um potencial de R$ 60.000 mensais em R$ 36.000 ou menos, acelerando a perda de mercado." },
    { titulo: "Riscos de Não Conformidade e Multas Regulamentares", descricao: "A conformidade regulatória é crítica para minimercados que comercializam alimentos, produtos de higiene e bebidas. Não mapear exigências traz risco de multas, interdições e perda de credibilidade. É preciso observar normas da ANVISA relacionadas a boas práticas de armazenamento, rotulagem e manuseio, requisitos do MAPA para produtos de origem animal e fiscalizações da Vigilância Sanitária municipal e estadual. Além disso, alvará de funcionamento da Prefeitura, vistoria do Corpo de Bombeiros e regularização fiscal com a Secretaria da Fazenda (Sefaz) são obrigatórios. A legislação consumerista (Procon) impõe regras de informação de preços e política de trocas. Falhas em controle de validade, rastreabilidade de lotes e emissão de notas fiscais eletrônicas podem gerar autuações, apreensão de mercadorias e necessidade de adequações emergenciais muito custosas. O planejamento mapeia obrigações, prazos de renovação de licenças e processos necessários para manter operação regular e segura.", custoReal: "Multas e custos de adequação emergencial por não conformidade podem ultrapassar R$ 20.000 a R$ 50.000, além do impacto de perda de vendas por interdição temporária." },
    { titulo: "Crescimento Desordenado e Falta de Processos Escaláveis", descricao: "Crescer sem processos definidos compromete qualidade, margem e experiência do cliente. Minimercados que expandem o mix, canais ou pontos de venda sem padronizar processos operacionais e sistemas de controle enfrentam ruptura de atendimento, erros de estoque e custos operacionais crescentes. A ausência de indicadores (KPIs) claros, descrição de funções e governança resulta em sobrecarga da gestão, alta rotatividade e perda de eficiência. Sem processos escaláveis para compras, reposição, precificação dinâmica e gestão de equipe, a expansão corrói rentabilidade. O plano de negócios define roadmap de crescimento, descreve processos críticos, dimensiona equipe e tecnologia e estabelece métricas para monitorar saúde do negócio durante a escala.", custoReal: "Crescimento sem processos pode aumentar custos operacionais em 15% a 30%, reduzindo o lucro operacional e exigindo investimentos extras para reestruturação." }
  ],
    custosConclusao: [
    "Investir em consultoria e em um plano de negócios para minimercado é mais economia do que gasto: evita erros de precificação, problemas de fluxo de caixa, falhas de posicionamento e riscos regulatórios que geram prejuízos muito maiores do que o custo do serviço. Um plano profissional oferece diagnóstico, cenário financeiro, plano de ação e roadmap de implementação que protegem capital, orientam decisões e aumentam a probabilidade de sucesso. Com metodologia da ECONOMICA, você transforma conhecimento de mercado em decisões operacionais e financeiras precisas, garantindo que cada real investido tenha retorno mensurável e riscos devidamente mitigados.",
    "Não se pergunte quanto custa fazer um plano. Pergunte-se: quanto me custará não ter um?"
  ],
    
    // DETALHES
    detalhesH3: "5 Detalhes Cruciais que Muitos Empreendedores de minimercado Esquecem",
    detalhesIntroducao: [
    "Ter paixão e conhecimento do produto não basta para gerir um minimercado com sucesso. A gestão empresarial exige disciplina em finanças, estratégia e governança. Erros em cálculo de margem, prazos de pagamento, mapa de clientes e conformidade regulatória podem consumir rapidamente capital e reputação. São detalhes que passam despercebidos quando a operação é gerida por intuição, mas que comprometem sustentabilidade e escalabilidade do negócio.",
    "Esses detalhes vão além do conhecimento técnico: definem regras de preço, limites de risco, políticas de estoque e indicadores que separariam um negócio que sobrevive de um que prospera. O planejamento profissional sistematiza esses pontos e transforma operações reativas em processos previsíveis e rentáveis."
  ],
    detalhes: [
    { titulo: "O Cálculo Preciso do Capital de Giro", descricao: "Capital de giro é o recurso necessário para manter o minimercado operando até que as receitas cubram as despesas regulares. Vai além do investimento inicial: inclui compras de estoque, prazos entre compra e venda, contas a pagar, impostos e pagamento de salários. Minimercados costumam ter ciclo de estoque curto, mas precisam de fluxo para repor categorias essenciais e atender sazonalidade. Subestimar esse montante gera compras parceladas, custo financeiro e ruptura de sortimento, reduzindo vendas. Uma análise robusta identifica necessidades por categoria, prazo médio de recebimento e pagamento e monta reservas para 6-12 meses.", solucao: "No plano de negócios projetamos fluxo de caixa mensal específico do minimercado, considerando sazonalidade, prazos com fornecedores e política de estoque. Calculamos capital de giro necessário para 6-12 meses, indicando linhas de financiamento apropriadas e estratégias de negociação para reduzir necessidade de capital." },
    { titulo: "Licenças, Vigilância e Obrigações Legais", descricao: "Minimercados estão sujeitos a um conjunto de normas e licenças: alvará de funcionamento da Prefeitura, vistoria do Corpo de Bombeiros, registros na Vigilância Sanitária municipal e estadual, cumprimento de regras da ANVISA quanto a armazenamento e manipulação, e exigências do MAPA para produtos de origem animal. Há também obrigações fiscais com a Secretaria da Fazenda (Sefaz), emissão de notas eletrônicas e regras do Código de Defesa do Consumidor fiscalizadas por Procon. Documentação incompleta ou não conformidade em rotulagem e validade pode resultar em multas, apreensão de produtos e interdição temporária.", solucao: "O plano mapeia todas as licenças e prazos de renovação, define responsáveis por cada etapa e inclui checklist de conformidade. Assim evitamos autuações e antecipamos adequações, reduzindo custos e garantindo operação contínua desde a abertura." },
    { titulo: "Mix de Produtos e Estratégia de Receitas", descricao: "Definir mix de produtos para minimercado exige cruzar demanda local com margem e rotação. Nem todo item que vende bem traz margem adequada; categorias com alta rotatividade e margem baixa podem ser complementadas por itens de maior margem e serviços agregados. É preciso considerar sazonalidade, promoções, marcas próprias, acordos com fornecedores e condições de compra. Além disso, canais como delivery e vendas por WhatsApp alteram custo por pedido e impactam margem final.", solucao: "O plano ajuda a montar portfólio inicial inteligente, priorizando SKUs estratégicos, definindo margem alvo por categoria e sugerindo fontes de receita complementares (serviços, parcerias, campanhas locais) para maximizar rentabilidade." },
    { titulo: "O Custo Real por Unidade de Operação", descricao: "Calcular custo operacional por unidade significa consolidar todos os custos fixos (aluguéis, energia, salários, impostos) e variáveis (compras, frete, embalagens) e dividir pela unidade relevante: vendas diárias, tickets ou clientes atendidos. Esse cálculo revela o preço mínimo necessário para cobrir operações e alcançar margem desejada. Sem essa visão, promoções ou descontos podem parecer atraentes no curto prazo, mas corroer lucro em volume. Conhecer custo por unidade também orienta decisão sobre mix, tamanho de pedidos e metas de vendas.", solucao: "No plano calculamos ponto de equilíbrio operacional e custo por unidade para seu minimercado, estabelecendo metas de faturamento e indicadores de eficiência que guiam decisões comerciais e de precificação." },
    { titulo: "O Plano de Marketing e Aquisição de Clientes", descricao: "Trazer clientes desde a abertura exige estratégia: marketing local, presença digital e parcerias. Canais eficazes para minimercado incluem redes sociais segmentadas, anúncios locais, programas de fidelidade, parcerias com condomínios e comércios vizinhos, além de integração com plataformas de delivery e uso de WhatsApp Business para pedidos e comunicação. Calcular custo de aquisição por canal e retorno por cliente é essencial para priorizar investimentos e manter fluxo constante.", solucao: "O plano estrutura ações de marketing com cronograma, orçamento e metas, definindo canais prioritários, conteúdo, promoções e métricas para medir CAC e LTV, garantindo atração e retenção contínua de clientes." }
  ],
    detalhesConclusao: [
    "Esses cinco pontos são apenas a ponta do iceberg: gerir um minimercado com sucesso exige planejamento profissional e disciplina de gestão. O plano de negócios transforma experiência técnica em decisões financeiras e estratégicas mensuráveis, reduz riscos e cria roteiro de crescimento sustentável."
  ],
    
    // ITENS INCLUÍDOS
    itensIncluidosH3: "O Que Está Incluído no Seu Plano de Negócios",
    itensIncluidos: [
    "Análise de viabilidade econômica específica para minimercado",
    "Definição de público-alvo e posicionamento no mercado de minimercado",
    "Planejamento operacional completo adaptado para minimercado",
    "Estratégias de marketing e aquisição de clientes para minimercado",
    "Projeções financeiras detalhadas (3-5 anos) para minimercado",
    "Análise de investimento inicial necessário para minimercado",
    "Plano de gestão e recursos humanos para minimercado",
    "Indicadores de desempenho (KPIs) específicos para minimercado"
  ],
    
    // FAQ (vazio - LLM não gera)
    faqH3: "Perguntas Frequentes",
    faq: [],
    
    // CTA
    ctaH3: "Pronto para Transformar minimercado em um Sucesso?",
  ctaP1: "Entre em contato conosco e solicite seu plano de negócios personalizado para minimercado.",
  ctaBotao: "Solicitar Plano de Negócios"
};